<a href="https://colab.research.google.com/github/harsh0309/Machine-Learning-Projects/blob/main/logistic_regression_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df=df[df['species']!='setosa']

In [ ]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [ ]:
df['species'] = df['species'].map({
    'versicolor': 0,
    'virginica': 1
})

/tmp/ipykernel_4463/3942393835.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['species'] = df['species'].map({

In [ ]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [ ]:

X=df.drop('species',axis=1)
y=df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[100 rows x 4 columns]

In [ ]:
y

50     0
51     0
52     0
53     0
54     0
      ..
145    1
146    1
147    1
148    1
149    1
Name: species, Length: 100, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
classifier=LogisticRegression()

In [ ]:
from inspect import Parameter
from sklearn.model_selection import GridSearchCV
Parameter = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100],
    'max_iter': [100,200,300]
}

In [ ]:
classifier_regressior=GridSearchCV(estimator=classifier,param_grid=Parameter,scoring='accuracy',cv=5)

In [ ]:
classifier_regressior.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
570 fits failed out of a total of 855.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
285 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
285 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [   nan 0.9625    nan    nan 0.9625    nan    nan 0.9625    nan    nan
 0.9625    nan    nan 0.9625    nan    nan 0.9625    nan    nan 0.9625
    nan    nan 0.9625    nan    nan 0.9625    nan    nan 0.975     nan
    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan
 0.975     nan    nan 0.975     nan    nan 0.9875    nan    nan 0.9875
    nan    nan 0.9875    nan    nan 0.9875    nan    nan 0.9875    nan
    nan 0.9875    nan    nan 0.9875    nan    nan 0.9875    nan    nan
 0.9875    nan    nan 0.9875    nan    nan 0.9875    nan    nan 0.9875
    nan    nan 0.9875    nan    nan 0.9875    nan    nan 0.9875    nan
    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan
 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan 0.975
    nan    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan
    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan
 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan 0.975
    nan    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan
    nan 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan
 0.975     nan    nan 0.975     nan    nan 0.975     nan    nan 0.975
    nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50,
                               60, 70, 80, 90, 100],
                         'max_iter': [100, 200, 300],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [ ]:
print(classifier_regressior.best_params_)

{'C': 6, 'max_iter': 100, 'penalty': 'l2'}

In [ ]:
print(classifier_regressior.best_score_)

0.9875

In [ ]:
##prediction
y_pred=classifier_regressior.predict(X_test)

In [ ]:
##Accurecy score
from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_pred,y_test)

In [ ]:
print(score)

0.9

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.80      0.89        10

    accuracy                           0.90        20
   macro avg       0.92      0.90      0.90        20
weighted avg       0.92      0.90      0.90        20